steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - beta
  - functions
  - deploy
  - image_labeller_process_subscriber
  - --runtime python37
  - --source=.
  - --trigger-http
  - --allow-unauthenticated